version: "3.9"
services:
  web:
    container_name: currency-converter
    build:
      context: .
      target: runner
    environment:
      NODE_ENV: production
      FRANKFURTER_BASE: https://api.frankfurter.dev/v1
      OPEN_ER_API_BASE: https://open.er-api.com/v6
      CURRENCY_API_CDN_BASE: https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: always